/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    Circle_3: THREE.Mesh;
    Circle_4: THREE.Mesh;
  };
  materials: {
    stem: THREE.MeshStandardMaterial;
    ["white stem"]: THREE.MeshStandardMaterial;
    ["yellow bud"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/PinkFlower-1619086549/pink_flower_01.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Circle"
          position={[-0.0151, 3.0637, 0.0133]}
          rotation={[Math.PI, -0.0259, Math.PI]}
          scale={[0.2974, 0.2974, 0.2974]}
        >
          <mesh
            name="Circle_1"
            geometry={nodes.Circle_1.geometry}
            material={materials.stem}
          />
          <mesh
            name="Circle_2"
            geometry={nodes.Circle_2.geometry}
            material={materials["white stem"]}
          />
          <mesh
            name="Circle_3"
            geometry={nodes.Circle_3.geometry}
            material={materials["yellow bud"]}
          />
          <mesh
            name="Circle_4"
            geometry={nodes.Circle_4.geometry}
            material={materials["Material.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
